# Generated by Django 4.0.6 on 2022-07-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('original_name', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('genre', models.CharField(max_length=10)),
                ('running_time', models.IntegerField()),
                ('director', models.CharField(max_length=30)),
                ('cast', models.TextField()),
                ('synopsis', models.TextField()),
                ('like', models.BooleanField(default=True)),
                ('dislike', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movieinfos',
            },
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaser', models.URLField()),
                ('shorts', models.URLField()),
                ('trailer', models.URLField()),
                ('movieinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.movieinfo')),
            ],
            options={
                'db_table': 'movievideos',
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('movieinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movieinfo')),
            ],
            options={
                'db_table': 'movieimages',
            },
        ),
    ]
